- hosts: publish
  remote_user: control
  tasks:
  - name: Update
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install Apache2
    become: yes
    apt:
      name: apache2
      state: present

  - name: Copie rep. web
    become: yes
    shell: cp -r /opt/code/html/ /var/www/

  - name: Démarrage apache2
    become: yes
    service:
      name: apache2
      state: started
      
  - name: Verification port 80
    wait_for:
      port: 80
      delay: 10
      msg: Fail apache2
