- hosts: publish
  remote_user: control
  tasks:
  - name: Update
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install Apache2
    become: yes
    apt:
      name: apache2
      state: present
    
  - name: Initilisation of the var file 
    shell: cp -r /opt/code/html/ /var/www/
    
  - name: Starting apache services
    shell: service apache2 start

  - name: Verification port 80
    wait_for:
      port: 80
      delay: 10
      msg: Fail apache2
